Machine learning- is an AI branch that involves algorithms to make prediction or decision based on data


**Steps**


*   Data Collection
*   Data Preproessing
*   Model selection
*   Train & Test the model
*   model deployment

**example**


*   Email Spam Filtering
*   Image Recogination

Recommendation System

Voice Assistants

Self driving Cars

Fraud Detection

Medical Diagnosis

Speech Recognition

Stock Market Prediction

Language Translation

Types of Algoritms

supervised learning-it type of Machine learning algoritms that learn from labelled data

classifaction-involes prdiction discreat albels or categoris such as "yes" or "no" different classes
eg-
logiacl Regression
Random Forese
Regession









**linner regression**

In [ ]:
import pandas as pd
import numpy as ny
from matplotlib import pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


salary=pd.read_csv("/content/drive/MyDrive/DSML-dataset/Salary.csv")
salary

,YearsExperience,Salary
0,1.1,39343
1,1.3,46205
2,1.5,37731
3,2.0,43525
4,2.2,39891
5,2.9,56642
6,3.0,60150
7,3.2,54445
8,3.2,64445
9,3.7,57189


**data preprocessing**

In [ ]:
salary.shape

(35, 2)

In [ ]:
salary.isna().sum()

,0
YearsExperience,0
Salary,0


In [ ]:
salary.dtypes

,0
YearsExperience,float64
Salary,int64


**model selection**

In [ ]:
x=salary.drop(['Salary'],axis=1)
y=salary['Salary']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

**traing and Testing**

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

pred_y=model.predict(x_test)
pred_y

array([ 67631.40503486,  80836.12861418,  45623.53240266, 120450.29935213,
       141577.85707904, 118689.66954156,  97562.11181465, 112527.46520454,
       111647.15029926, 136295.96764732,  74673.92427716])

**model Evaluation**

In [ ]:
model.score(x_test,y_test)

0.948425676671226

In [ ]:
new_data=pd.DataFrame([10],columns=x.columns)
prediction=model.predict(new_data)
print(prediction)

[116048.72482569]


mulitpile liner regssion

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/DSML-dataset/data.csv")
data



,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA


In [ ]:
data.shape #returns the no of rows and colums (dimesnison of the )

(4600, 18)

In [ ]:
data.dtypes #

,0
date,object
price,float64
bedrooms,float64
bathrooms,float64
sqft_living,int64
sqft_lot,int64
floors,float64
waterfront,int64
view,int64
condition,int64


In [ ]:
# this method to change the object into int value
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
data['street']=label_encoder.fit_transform(data['street'])
data['street'].unique()

array([1522, 3899, 2291, ..., 4033, 3498, 1514])

In [ ]:
label_encoder=preprocessing.LabelEncoder()
data['city'] = label_encoder.fit_transform(data['city'])
data['city'].unique()

array([36, 35, 18,  3, 31, 21, 27, 20, 33,  1, 10,  5, 14, 19, 16, 42, 26,
       13, 32,  7, 38, 11,  6,  9, 15, 17, 25, 23,  4, 30,  8,  0, 37, 40,
       41, 43, 34, 22, 12, 39, 28,  2, 29, 24])

In [ ]:
label_encoder=preprocessing.LabelEncoder()
data['statezip'] = label_encoder.fit_transform(data['statezip'])
data['statezip'].unique()

array([62, 58, 26,  7, 31, 54, 23, 27, 67, 48, 42, 49,  6, 45, 73,  5, 46,
        9, 60,  2, 63, 21, 17, 56, 22, 41, 13, 50, 68, 55, 14, 33, 44, 15,
       37, 43, 10, 38, 74, 32, 36, 59, 47, 53,  4, 57, 70,  3, 11, 64, 69,
        0, 34, 65, 16, 66, 35, 25,  8, 30, 19, 52, 18, 61, 20, 71, 75, 51,
       40, 72,  1, 24, 12, 39, 28, 29, 76])

In [ ]:
label_encoder=preprocessing.LabelEncoder()
data['country'] = label_encoder.fit_transform(data['country'])
data['country'].unique()

array([0])

In [ ]:
label_encoder=preprocessing.LabelEncoder()
data['date'] = label_encoder.fit_transform(data['date'])
data['date'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [ ]:
data.dtypes

,0
date,int64
price,float64
bedrooms,float64
bathrooms,float64
sqft_living,int64
sqft_lot,int64
floors,float64
waterfront,int64
view,int64
condition,int64


In [ ]:
# x=salary.drop(['Salary'],axis=1)
# y=salary['Salary']

x=data.drop(['price'],axis=1)
y=data['price']
y.head()

,price
0,313000.0
1,2384000.0
2,342000.0
3,420000.0
4,550000.0


In [ ]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)


In [ ]:

model=LinearRegression()
model.fit(x_train,y_train)

pred_y=model.predict(x_test)
pred_y

array([ 486093.28896555,  672233.17824144,  273218.87678953, ...,
        420199.58803453, 1020075.5457639 ,  678806.64057681])

In [ ]:
model.score(x_test,y_test)

0.47635925476628915

In [ ]:
# to predict the price of a house
new_data=pd.DataFrame([[2,3,2,1200,1450,560,2020,2012,1522,56,18,1500,1000,12,120,120,120]],columns=x.columns)
prediction=model.predict(new_data)
print(prediction)

[1.26070464e+09]
